# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u7ec4',
                'verbose_name_plural': '\u9879\u76ee\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4efb\u52a1\u540d')),
                ('jobs_type', models.CharField(blank=True, choices=[(b'1', 'php'), (b'2', 'java'), (b'3', 'net'), (b'4', 'python'), (b'5', 'node')], max_length=30, null=True, verbose_name='\u9879\u76ee\u8bed\u8a00\u7c7b\u578b')),
                ('code_repo', models.CharField(blank=True, choices=[(b'1', 'git'), (b'2', 'svn'), (b'3', 'ftp')], max_length=30, null=True, verbose_name='\u4ee3\u7801\u4ed3\u5e93')),
                ('code_url', models.CharField(blank=True, choices=[(b'1', 'git'), (b'2', 'svn'), (b'3', 'ftp')], max_length=30, null=True, verbose_name='\u4ee3\u7801\u5730\u5740')),
                ('code_branch', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4ee3\u7801\u5206\u652f')),
                ('code_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4ee3\u7801\u7248\u672c')),
                ('deploy_script', models.TextField(blank=True, null=True, verbose_name='\u53d1\u5e03\u811a\u6b65')),
                ('deploy_test', models.TextField(blank=True, null=True, verbose_name='\u53d1\u5e03\u6d4b\u8bd5')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9879\u76ee\u63cf\u8ff0')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobGroup', verbose_name='\u4efb\u52a1\u7ec4')),
                ('hosts', models.ManyToManyField(to='hosts.Host', verbose_name='\u88ab\u53d1\u5e03\u7684\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u6216\u4efb\u52a1',
                'verbose_name_plural': '\u9879\u76ee\u6216\u4efb\u52a1',
            },
        ),
    ]
