# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='deploy_env',
            field=models.CharField(blank=True, choices=[(b'1', 'test'), (b'2', 'stagging'), (b'3', 'pre'), (b'4', 'prod')], max_length=30, null=True, verbose_name='\u53d1\u5e03\u73af\u5883'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='deploy_vars',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53d1\u5e03\u53c2\u6570'),
        ),
    ]
