# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170727_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cost_time',
            field=models.DateTimeField(null=True, verbose_name='\u53d1\u5e03\u8017\u65f6'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='deploy_status',
            field=models.CharField(blank=True, choices=[(b'1', '\u672a\u6267\u884c'), (b'2', '\u53d1\u5e03\u4e2d'), (b'3', '\u53d1\u5e03\u6210\u529f'), (b'4', '\u53d1\u5e03\u5931\u8d25')], max_length=30, null=True, verbose_name='\u53d1\u5e03\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
