# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170727_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.JobGroup', verbose_name='\u4efb\u52a1\u7ec4'),
        ),
    ]
