# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='saltserver',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='saltserver',
            name='url',
        ),
        migrations.AddField(
            model_name='saltserver',
            name='apiurl',
            field=models.URLField(blank=True, verbose_name='api\u5730\u5740'),
        ),
        migrations.DeleteModel(
            name='Idc',
        ),
    ]
